const ALLOWED_ORIGINS=new Set(['https://mavurioficial.github.io','https://mavuri-api-test.vercel.app']);
const BASE_RESOLVER='https://mavuri-api-test.vercel.app/api/resolve6';
const VERSION='2026.08.31.17';
const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126 Safari/537.36';
function cors(req,res){const o=req.headers.origin||'';if(ALLOWED_ORIGINS.has(o)){res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin')}res.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type')}
function first(...values){for(const v of values.flat(Infinity)){if(v&&typeof v==='object'){const n=v.name||v.label||v.title;if(n&&typeof n!=='object'){const s=String(n).trim();if(s)return s}continue}const s=String(v??'').trim();if(s)return s}return ''}
function number(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;const s=String(v).replace(/[^0-9,.-]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null}
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function similarity(a,b){const x=new Set(norm(a).split(' ').filter(Boolean)),y=new Set(norm(b).split(' ').filter(Boolean));if(!x.size||!y.size)return 0;let n=0;for(const w of x)if(y.has(w))n++;return n/Math.max(x.size,y.size)}
function meta(html,names){for(const name of names){const e=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');for(const p of [new RegExp(`<meta[^>]+(?:property|name)=[\"']${e}[\"'][^>]+content=[\"']([^\"']*)[\"'][^>]*>`,'i'),new RegExp(`<meta[^>]+content=[\"']([^\"']*)[\"'][^>]+(?:property|name)=[\"']${e}[\"'][^>]*>`,'i')]){const m=String(html||'').match(p);if(m?.[1])return m[1].replace(/&quot;/g,'\"').replace(/&amp;/g,'&').trim()}}return ''}
function jsonBlocks(html){const out=[];for(const m of String(html||'').matchAll(/<script[^>]+type=[\"']application\/(?:ld\+json|json)[\"'][^>]*>([\s\S]*?)<\/script>/gi)){try{out.push(JSON.parse(m[1].trim()))}catch{}}return out}
function walk(v,fn,seen=new Set()){if(!v||typeof v!=='object'||seen.has(v))return;seen.add(v);fn(v);if(Array.isArray(v))for(const x of v)walk(x,fn,seen);else for(const x of Object.values(v))walk(x,fn,seen)}
async function get(url,headers={}){try{return await fetch(url,{redirect:'follow',cache:'no-store',headers:{'user-agent':UA,'accept-language':'pt-BR,pt;q=0.9',...headers}})}catch{return null}}
async function jina(url){try{const r=await fetch(`https://r.jina.ai/${url}`,{headers:{'user-agent':UA,'accept':'text/plain'},cache:'no-store'});if(!r.ok)return '';return await r.text()}catch{return ''}}
async function json(url){const r=await get(url,{accept:'application/json'});if(!r?.ok)return null;try{return await r.json()}catch{return null}}
function keyNumber(html,names){const s=String(html||'');for(const name of names){const re=new RegExp(`(?:[\"']${name}[\"']|${name})\\s*[:=]\\s*[\"']?([0-9]+(?:[.,][0-9]+)?)`,'i');const m=s.match(re);if(m){const n=number(m[1]);if(n!==null)return n}}return null}
function textPrices(html){const text=String(html||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&');const out=[];for(const m of text.matchAll(/R\$\s*([0-9]{1,3}(?:\.[0-9]{3})*(?:,[0-9]{1,2})?)/gi)){const n=number(m[1]);if(n!==null&&n>0&&!out.includes(n))out.push(n)}return out}
function markdownData(text){const s=String(text||'');let title=first(s.match(/^#\s+(.+)$/m)?.[1]);let previousPrice=null,currentPrice=null;const old=s.match(/~~R\$\s*([0-9.]+(?:,[0-9]{1,2})?)~~/i);if(old)previousPrice=number(old[1]);const prices=textPrices(s);if(prices.length)currentPrice=prices.find(n=>n!==previousPrice)||prices[0]||null;let category='';const rank=s.match(/\d+º em ([^\n]+)/i);if(rank)category=rank[1].replace(/\s+Growth Supplements.*$/i,'').trim();return{title,price:currentPrice,previousPrice,category}}
function categoryFromNode(n){let c=first(n.category,n.categoryName,n.category_name,n.category_id,n.categoryId);if(c)return c;const b=n.breadcrumb||n.breadcrumbs||n.itemListElement;if(Array.isArray(b)){for(let i=b.length-1;i>=0;i--){const x=first(b[i]?.name,b[i]?.item?.name,b[i]?.label);if(x)return x}}return first(b?.name,b?.item?.name)}
function pageData(html){let title='',price=null,previousPrice=null,category='',categoryId='';for(const b of jsonBlocks(html)){walk(b,n=>{if(!title)title=first(n.name,n.title,n.productName);if(price===null)price=number(n.price,n.current_price,n.currentPrice,n.sale_price,n.salePrice,n.offers?.price,Array.isArray(n.offers)?n.offers[0]?.price:null);if(previousPrice===null)previousPrice=number(n.originalPrice,n.original_price,n.listPrice,n.list_price,n.regularPrice,n.regular_price,n.oldPrice,n.old_price,n.offers?.highPrice,n.offers?.regularPrice,Array.isArray(n.offers)?n.offers[0]?.highPrice:null);if(!category){category=categoryFromNode(n);if(/^MLB[-_]?\d+$/i.test(category)){categoryId=category;category=''}}if(!categoryId)categoryId=first(n.category_id,n.categoryId,n.categoryIdMLB)})}title=first(title,meta(html,['og:title','twitter:title']).replace(/\s*\|\s*Mercado Livre.*$/i,''));price=price??number(meta(html,['product:price:amount','og:price:amount']));previousPrice=previousPrice??keyNumber(html,['original_price','originalPrice','regular_amount','regularAmount','list_price','listPrice','old_price','oldPrice']);return{title,price,previousPrice,category,categoryId}}
function categoryIdValue(v){const s=String(v||'').trim();return /^MLB-\d+$/i.test(s)?s.replace('-',''):s}
async function categoryName(id){if(!id)return '';const c=await json(`https://api.mercadolibre.com/categories/${encodeURIComponent(categoryIdValue(id))}`);return first(c?.name,c?.path_from_root?.at(-1)?.name,c?.path_from_root?.[0]?.name)}
function titleFromUrl(url){try{const u=new URL(url);const slug=u.pathname.split('/').filter(Boolean)[0]||'';return decodeURIComponent(slug).replace(/[-_]+/g,' ').replace(/\s+/g,' ').trim()}catch{return ''}}
async function enrich(product){const id=String(product.productId||'').toUpperCase();const catalog=await json(`https://api.mercadolibre.com/products/${encodeURIComponent(id)}`);if(catalog){product.name=first(product.name,catalog.name,catalog.family_name);product.categoryId=first(product.categoryId,catalog.category_id);const winner=catalog.buy_box_winner;if(winner?.item_id){product.itemId=String(winner.item_id).toUpperCase();product.price=number(winner.price)??product.price;product.previousPrice=number(winner.original_price)??product.previousPrice}}if(product.itemId){const item=await json(`https://api.mercadolibre.com/items/${encodeURIComponent(product.itemId)}`);if(item){product.name=first(product.name,item.title);product.categoryId=first(product.categoryId,item.category_id);product.price=number(item.price)??product.price;product.previousPrice=number(item.original_price)??product.previousPrice}}if(!product.previousPrice||product.previousPrice<=product.price){const sale=product.itemId?await json(`https://api.mercadolibre.com/items/${encodeURIComponent(product.itemId)}/sale_price?context=channel_marketplace`):null;if(sale){product.price=number(sale.amount)??product.price;product.previousPrice=number(sale.regular_amount)??product.previousPrice}}product.category=first(product.category,await categoryName(product.categoryId));product.name=first(product.name,'0');product.category=first(product.category,'0');product.price=product.price??0;product.previousPrice=product.previousPrice??0;product.installments=product.installments??0;product.discount=product.price>0&&product.previousPrice>product.price?Math.round((product.previousPrice-product.price)/product.previousPrice*100):0;return product}
async function socialFallback(product,socialUrl){if(!socialUrl||product.price>0&&product.previousPrice>0)return product;const r=await get(socialUrl,{accept:'text/html,application/xhtml+xml'});if(!r?.ok)return product;const html=await r.text();const text=String(html).replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();const titleWords=norm(product.name).split(' ').filter(Boolean).slice(0,4);const hay=norm(text);const needle=titleWords.join(' ');const idx=needle?hay.indexOf(needle):-1;const region=idx>=0?text.slice(Math.max(0,idx-100),idx+800):text;const prices=textPrices(region);if(prices.length){const promo=/\d+%\s*OFF/i.test(region);if(promo&&prices.length>=2){product.previousPrice=product.previousPrice>0?product.previousPrice:Math.max(...prices);if(product.price<=0)product.price=Math.min(...prices)}else if(product.price<=0)product.price=prices[0]}return product}
async function searchFallback(product){const query=first(product.name,titleFromUrl(product.url));if(!query||query==='0')return product;const words=norm(query).split(' ').filter(Boolean).slice(0,5);const shortQuery=words.join(' ');const url='https://lista.mercadolivre.com.br/'+encodeURIComponent(shortQuery.replace(/\s+/g,'-'));const r=await get(url,{accept:'text/html,application/xhtml+xml'});let html=r?.ok?await r.text():'';if(!html||html.length<1000)html=await jina(url);const md=markdownData(html);if(!product.name||product.name==='0')product.name=first(md.title,query);if(product.previousPrice<=product.price&&md.previousPrice)product.previousPrice=md.previousPrice;if(product.price<=0&&md.price)product.price=md.price;if(product.category==='0'&&md.category)product.category=md.category;const prices=textPrices(html);if(product.price<=0){const currentCandidates=product.previousPrice>0?prices.filter(n=>n!==product.previousPrice):prices;if(currentCandidates.length)product.price=currentCandidates[0]}const candidates=[];for(const b of jsonBlocks(html))walk(b,n=>{const t=first(n.title,n.name,n.productName);if(!t)return;const p=number(n.price,n.current_price,n.currentPrice,n.sale_price,n.salePrice,n.item?.price,n.product?.price,n.offers?.price,Array.isArray(n.offers)?n.offers[0]?.price:null);const old=number(n.original_price,n.originalPrice,n.list_price,n.regular_price,n.item?.original_price,n.offers?.highPrice,Array.isArray(n.offers)?n.offers[0]?.highPrice:null);const cid=first(n.category_id,n.categoryId,n.item?.category_id,n.product?.category_id);candidates.push({title:t,price:p,previousPrice:old,categoryId:cid,score:similarity(query,t)})});candidates.sort((a,b)=>b.score-a.score);const best=candidates.find(x=>x.score>=0.65)||candidates[0];if(best){product.name=first(product.name,best.title);if(product.price<=0)product.price=best.price??0;if(product.previousPrice<=product.price&&best.previousPrice)product.previousPrice=best.previousPrice;product.categoryId=first(product.categoryId,best.categoryId);product.category=first(product.category,await categoryName(product.categoryId))}if(product.category==='0'){const lower=norm(query);if(lower.includes('creatina'))product.category='Creatina';else if(lower.includes('starlink')||lower.includes('internet')||lower.includes('antena'))product.category='Conectividade e Redes'}product.discount=product.price>0&&product.previousPrice>product.price?Math.round((product.previousPrice-product.price)/product.previousPrice*100):0;return product}
export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({message:'Método não permitido.'});const affiliateUrl=String(req.query?.url||'').trim();if(!affiliateUrl)return res.status(400).json({message:'Informe o parâmetro url.'});try{const u=new URL(BASE_RESOLVER);u.searchParams.set('url',affiliateUrl);const base=await json(u.toString());if(!base?.productUrl)return res.status(200).json({...base,resolverVersion:VERSION});const response=await get(base.productUrl,{accept:'text/html,application/xhtml+xml'});const html=response?await response.text():'';const parsed=pageData(html);const product={productId:base.productId||'',url:base.productUrl,name:first(parsed.title,base.product?.title,titleFromUrl(base.productUrl)),category:first(parsed.category,base.product?.category),categoryId:parsed.categoryId||'',price:parsed.price??number(base.product?.price),previousPrice:parsed.previousPrice??number(base.product?.previousPrice),installments:number(base.product?.installments),source:'real-product-page-html'};if(!product.name||product.name==='0'||product.price===null||product.price===0||!product.category||product.category==='0'){const proxy=await jina(base.productUrl);if(proxy){const md=markdownData(proxy);product.name=first(product.name,md.title);product.price=product.price>0?product.price:(md.price??0);product.previousPrice=product.previousPrice>0?product.previousPrice:(md.previousPrice??0);product.category=first(product.category,md.category)}}await enrich(product);await socialFallback(product,base.socialUrl);await searchFallback(product);product.name=first(product.name,'0');product.category=first(product.category,'0');product.price=product.price??0;product.previousPrice=product.previousPrice??0;const result={...base,resolverVersion:VERSION,product:{...product,id:product.productId,title:product.name}};return res.status(200).json(result)}catch(e){return res.status(502).json({ok:false,message:'Erro ao carregar os dados do anúncio real.',error:String(e?.message||e),resolverVersion:VERSION})}}