const ALLOWED_ORIGINS = new Set(['https://mavurioficial.github.io','https://mavuri-api-test.vercel.app']);
const BASE_RESOLVER = 'https://mavuri-api-test.vercel.app/api/resolve6';
const VERSION = '2026.08.31.09';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126 Safari/537.36';

function cors(req,res){const o=req.headers.origin||'';if(ALLOWED_ORIGINS.has(o)){res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin')}res.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type')}
function first(...values){for(const v of values.flat(Infinity)){if(typeof v!=='string'&&typeof v!=='number')continue;const s=String(v).trim();if(s)return s}return ''}
function number(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;const s=String(v).replace(/[^0-9,.-]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null}
function meta(html,names){for(const name of names){const e=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');for(const p of [new RegExp(`<meta[^>]+(?:property|name)=[\"']${e}[\"'][^>]+content=[\"']([^\"']*)[\"'][^>]*>`,'i'),new RegExp(`<meta[^>]+content=[\"']([^\"']*)[\"'][^>]+(?:property|name)=[\"']${e}[\"'][^>]*>`,'i')]){const m=String(html||'').match(p);if(m?.[1])return m[1].replace(/&quot;/g,'"').replace(/&amp;/g,'&').trim()}}return ''}
function jsonBlocks(html){const out=[];for(const m of String(html||'').matchAll(/<script[^>]+type=[\"']application\/(?:ld\+json|json)[\"'][^>]*>([\s\S]*?)<\/script>/gi)){try{out.push(JSON.parse(m[1].trim()))}catch{}}return out}
function walk(v,fn,seen=new Set()){if(!v||typeof v!=='object'||seen.has(v))return;seen.add(v);fn(v);if(Array.isArray(v))for(const x of v)walk(x,fn,seen);else for(const x of Object.values(v))walk(x,fn,seen)}
async function get(url,headers={}){try{return await fetch(url,{redirect:'follow',cache:'no-store',headers})}catch{return null}}
async function json(url){const r=await get(url,{accept:'application/json'});if(!r?.ok)return null;try{return await r.json()}catch{return null}}
function pageData(html){let title='',price=null,previousPrice=null,category='';for(const b of jsonBlocks(html)){walk(b,n=>{if(!title)title=first(n.name,n.title,n.productName);if(price===null)price=number(n.price,n.offers?.price,Array.isArray(n.offers)?n.offers[0]?.price:null);if(previousPrice===null)previousPrice=number(n.originalPrice,n.original_price,n.listPrice,n.list_price,n.regularPrice,n.regular_price,n.offers?.highPrice);if(!category)category=first(n.category,n.categoryName,n.category_name,n.category_id)})}title=first(title,meta(html,['og:title','twitter:title']).replace(/\s*\|\s*Mercado Livre.*$/i,''));price=price??number(meta(html,['product:price:amount','og:price:amount']));return{title,price,previousPrice,category}}
function categoryId(v){const s=String(v||'').trim();return /^MLB-\d+$/i.test(s)?s.replace('-',''):s}
async function categoryName(id){if(!id)return '';const c=await json(`https://api.mercadolibre.com/categories/${encodeURIComponent(id)}`);return first(c?.name,c?.path_from_root?.at(-1)?.name)}
async function enrich(product){const id=String(product.productId||'').toUpperCase();const catalog=await json(`https://api.mercadolibre.com/products/${encodeURIComponent(id)}`);if(catalog){product.name=first(product.name,catalog.name,catalog.family_name);product.categoryId=first(product.categoryId,catalog.category_id);const winner=catalog.buy_box_winner;if(winner?.item_id){product.itemId=String(winner.item_id).toUpperCase();product.price=number(winner.price)??product.price;product.previousPrice=number(winner.original_price)??product.previousPrice}}if(product.itemId){const item=await json(`https://api.mercadolibre.com/items/${encodeURIComponent(product.itemId)}`);if(item){product.name=first(product.name,item.title);product.categoryId=first(product.categoryId,item.category_id);product.price=number(item.price)??product.price;product.previousPrice=number(item.original_price)??product.previousPrice}}product.category=first(product.category,await categoryName(categoryId(product.categoryId)));if(product.itemId){const sale=await json(`https://api.mercadolibre.com/items/${encodeURIComponent(product.itemId)}/sale_price?context=channel_marketplace`);if(sale){product.price=number(sale.amount)??product.price;product.previousPrice=number(sale.regular_amount)??product.previousPrice}}product.name=first(product.name,'0');product.category=first(product.category,'0');product.price=product.price??0;product.previousPrice=product.previousPrice??0;product.installments=product.installments??0;product.discount=product.price>0&&product.previousPrice>product.price?Math.round((product.previousPrice-product.price)/product.previousPrice*100):0;return product}
export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({message:'Método não permitido.'});const affiliateUrl=String(req.query?.url||'').trim();if(!affiliateUrl)return res.status(400).json({message:'Informe o parâmetro url.'});try{const u=new URL(BASE_RESOLVER);u.searchParams.set('url',affiliateUrl);const base=await json(u.toString());if(!base?.productUrl)return res.status(200).json({...base,resolverVersion:VERSION});const response=await get(base.productUrl,{'user-agent':UA,'accept-language':'pt-BR,pt;q=0.9','accept':'text/html,application/xhtml+xml'});const html=response?await response.text():'';const parsed=pageData(html);const product={productId:base.productId||'',url:base.productUrl,name:first(parsed.title,base.product?.title),category:first(parsed.category,base.product?.category),price:parsed.price??number(base.product?.price),previousPrice:parsed.previousPrice??number(base.product?.previousPrice),installments:number(base.product?.installments),source:'real-product-page-html'};await enrich(product);const result={...base,resolverVersion:VERSION,product:{...product,id:product.productId,title:product.name}};return res.status(200).json(result)}catch(e){return res.status(502).json({ok:false,message:'Erro ao carregar os dados do anúncio real.',error:String(e?.message||e),resolverVersion:VERSION})}}